spring:
  application:
    name: priceFlow

  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/priceflow?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zbf103056

  # redis连接配置
  data:
    redis:
      host: 172.22.254.216
      port: 6379
      database: 0

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.qq.com
    port: 587
    username: 83430154@qq.com
    password: jgonhfxxahflbchb # 注意：是授权码，不是QQ登录密码
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8

mybatis:
    #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.priceflow.pojo.entity
  configuration:
      #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl